### ISSUE TITLE
Memory use still climbs on add_tags

### ISSUE THREAD

**Issue by jenningsanderson** [mapbox/osm-wayback#11]
Needs memory optimization: 1.5M features written ~ 5G of Memory use. This is likely a product of my C++ skills, a refactor by an experienced programmer could likely fix this quickly.

On the performance side, it's doing alright:
`add_tags` took 2m34s to process 1.7M features (Colorado). 

Other stats: 
colorado.osh.pbf = 281mb (A sizeable history file (~0.5% of the entire planet history file)
COLORADO_INDEX Directory = 2.4 G.  At this rate, the Planet could likely fit under 512 G !

/cc @lukasmartinelli @batpad

**Comment by lukasmartinelli** [comment]
> Needs memory optimization: 1.5M features written ~ 5G of Memory use. This is likely a product of my C++ skills, a refactor by an experienced programmer could likely fix this quickly.

I specified a memory buffer for RocksDB of 4GB (statically compiled, we can pass it in the options). So it might be it always reserves 4GB of memory for one layer of caching.

**Comment by lukasmartinelli** [comment]
Also storing the tags encoded as JSON is really not the most space efficient format :)
Was just the most convenient to get started. You can store any byte array in rocksdb. All that matters is encoding so it can be read again.

**Comment by lukasmartinelli** [comment]
fixed in https://github.com/mapbox/osm-tag-history/commit/4c59216891077dd05b71ec48f0f0e72eb8da7817
